class Api:
    get_ingredient_data  = "/ingredients"
    order_create = "/orders"
    order_get_list = "/orders/all"
    password_recover = "/password-reset"
    save_password_recover = "/reset"
    user_create = "/auth/register"
    user_login = "/auth/login"
    user_get_data = "/auth/user"
    user_logout = "/auth/logout"
    refresh_token = "/auth/token"
class Urls:
    base_url = "https://stellarburgers.nomoreparties.site/api"
    url_get_ingredient_data = f"{base_url}{Api.get_ingredient_data}"
    url_order_create = f"{base_url}{Api.order_create}"
    url_order_get_list = f"{base_url}{Api.order_get_list}"
    url_password_recover = f"{base_url}{Api.password_recover}"
    url_save_password_recover = f"{base_url}{Api.save_password_recover}"
    url_user_create = f"{base_url}{Api.user_create}"
    url_user_delete = f"{base_url}{Api.user_get_data}"
    url_user_login = f"{base_url}{Api.user_login}"
    url_user_get_data = f"{base_url}{Api.user_get_data}"
    url_user_logout = f"{base_url}{Api.user_logout}"
    url_refresh_token = f"{base_url}{Api.refresh_token}"